export const LOGIN = 'LOGIN';
export const GET_CURRENT_ACCOUNT = 'GET_CURRENT_ACCOUNT';

export const FETCH_ALL = 'FETCH_ALL';
export const UPDATE_PLANS = 'UPDATE_PLANS';

export const CREATE_DESK = 'CREATE_DESK';
export const UPDATE_DESK = 'UPDATE_DESK';
export const DELETE_DESK = 'DELETE_DESK';

export const FETCH_DESK_ASSIGNMENTS = 'FETCH_DESK_ASSIGNMENTS';
export const FETCH_CHANGESETS = 'FETCH_CHANGESETS';
export const UPDATE_DESK_ASSIGNMENTS = 'UPDATE_DESK_ASSIGNMENTS';
