export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const GET_CURRENT_ACCOUNT = 'GET_CURRENT_ACCOUNT';

export const FETCH_ALL = 'FETCH_ALL';
export const UPDATE_PLANS = 'UPDATE_PLANS';

export const CREATE_DESK = 'CREATE_DESK';
export const UPDATE_DESK = 'UPDATE_DESK';
export const DELETE_DESK = 'DELETE_DESK';

export const FETCH_DESK_ASSIGNMENTS = 'FETCH_DESK_ASSIGNMENTS';
export const UPDATE_DESK_ASSIGNMENTS = 'UPDATE_DESK_ASSIGNMENTS';

export const FETCH_PLAN_CHANGESETS = 'FETCH_CHANGESETS';
export const FETCH_PLAN_CHANGESET = 'FETCH_PLAN_CHANGESET';
export const UPDATE_PLAN_CHANGESETS = 'UPDATE_PLAN_CHANGESETS';
export const REPLACE_PLAN_CHANGESET = 'REPLACE_PLAN_CHANGESET';
export const COMPLETE_CHANGESET = 'COMPLETE_CHANGESET';

export const FETCH_CHANGESET_ITEMS = 'FETCH_CHANGESET_ITEMS';
export const UPDATE_CHANGESET_ITEMS = 'UPDATE_CHANGESET_ITEMS';
export const CREATE_CHANGESET_ITEM = 'CREATE_CHANGESET_ITEM';
export const REMOVE_DESK_OWNER = 'REMOVE_DESK_OWNER';
export const ASSIGN_DESK_OWNER = 'ASSIGN_DESK_OWNER';

export const SELECT_PLAN = 'SELECT_PLAN';
export const SELECT_BUILDING = 'SELECT_BUILDING';
export const SELECT_FLOOR = 'SELECT_FLOOR';

export const BROADCAST_NOTIFICATION = 'BROADCAST_NOTIFICATION';
export const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION';
